2025-05-08 22:18:08 JST

diff --git a/.bin/fetch-tf-provider-gihub-release b/.bin/fetch-tf-provider-gihub-release
--- a/.bin/fetch-tf-provider-gihub-release
+++ b/.bin/fetch-tf-provider-gihub-release
@@ -91,22 +91,22 @@ done
 shift $((OPTIND - 1))
 
 if [ -z "${HOSTNAME-}" ] || [[ $HOSTNAME = *[[:space:]]* ]]; then
-    printf "\033[1m[ERROR]: Missting argument -H <hostname>.\033[m\n\n" >&2
+    printf "\033[1m[ERROR]: Missing/Invalid argument -H <hostname>.\033[m\n\n" >&2
     echo "$USAGE" >&2
     exit 1
 fi
 if [ -z "${NAMESPACE-}" ] || [[ $NAMESPACE = *[[:space:]]* ]]; then
-    printf "\033[1m[ERROR]: Missting argument -N <namespace>.\033[m\n\n" >&2
+    printf "\033[1m[ERROR]: Missing/Invalid argument -N <namespace>.\033[m\n\n" >&2
     echo "$USAGE" >&2
     exit 1
 fi
 if [ -z "${TYPE-}" ] || [[ $TYPE = *[[:space:]]* ]]; then
-    printf "\033[1m[ERROR]: Missting argument -T <type>.\033[m\n\n" >&2
+    printf "\033[1m[ERROR]: Missing/Invalid argument -T <type>.\033[m\n\n" >&2
     echo "$USAGE" >&2
     exit 1
 fi
 if [ -z "${REPOSITORY-}" ] || [[ $REPOSITORY = *[[:space:]]* ]]; then
-    printf "\033[1m[ERROR]: Missting argument -R <repository>.\033[m\n\n" >&2
+    printf "\033[1m[ERROR]: Missing/Invalid argument -R <repository>.\033[m\n\n" >&2
     echo "$USAGE" >&2
     exit 1
 fi
